export type Language = 'ko' | 'en';

export const content = {
  ko: {
    skip: '본문으로 건너뛰기',
    nav: {
      product: '제품',
      analysis: '분석',
      security: '보안',
      workflow: '사용 방법',
      faq: '자주 묻는 질문',
      download: 'Windows 다운로드',
    },
    hero: {
      eyebrow: 'Windows 공개 베타 · 무료',
      title: <>내 거래에서 <br className="mobile-only" />패턴을 찾고,<br /><span>더 나은 기준을 만드세요.</span></>,
      copy: '읽기 전용으로 종료 거래를 가져와 저널에 남기고, 전략 규칙을 실제 실행과 대조하세요. 거래 복기와 분석 작업공간이 관찰된 패턴을 근거 거래까지 연결합니다.',
      secondary: '어떻게 작동하나요?',
      facts: ['회원가입 불필요', '읽기 전용 API', '내 컴퓨터에 저장'],
      visualLabel: '실제 Trade Journal 화면',
      visualTitle: '상세 거래 분석',
      visualCopy: '결론 → 근거 → 실제 거래까지',
      openImage: '실제 제품 화면 크게 보기',
      imageAlt: '시장 상황별 성과와 근거 거래를 보여주는 Trade Journal 상세 거래 분석 화면',
    },
    problem: {
      eyebrow: '왜 Trade Journal인가',
      title: <>기억은 선택적이지만,<br /><span>거래 기록은 그렇지 않습니다.</span></>,
      copy: '“이 전략은 잘 작동한다”, “계획대로 실행했다”, “이 장세에서는 약하다.” 매매에 대한 확신은 쉽게 생기지만, 기억만으로는 전략과 실행을 구분하기 어렵습니다.',
      questions: [
        ['나는 무엇을 거래했나?', '종료 거래와 계획·태그·전략·결과를 한 저널에서 확인'],
        ['전략 규칙을 지켰나?', '거래에 연결된 정확한 플레이북 버전으로 준수·위반 판정'],
        ['손실은 전략인가, 실행인가?', '거래 복기에서 전략과 실행 차이를 근거 거래까지 추적'],
      ],
      closing: '분석은 거래 기록에서 관찰된 연관성을 보여줍니다. 원인이나 미래 성과를 단정하지 않습니다.',
    },
    flow: {
      eyebrow: '하나의 검토 흐름',
      title: <>거래에서 시작해,<br /><span>변화를 측정하는 데까지.</span></>,
      copy: '한 번의 결과를 넘어서 전략, 실행, 다음 계획과 행동 실험을 같은 기록 흐름으로 연결합니다.',
      steps: [
        ['거래', '종료 거래 동기화'],
        ['저널', '계획 · 태그 · 전략 기록'],
        ['복기', '거래 복기'],
        ['진단', '전략과 실행 비교'],
        ['계획', '계획 분석'],
        ['실험', '가설 · 기준 고정'],
        ['측정', '같은 정의로 비교'],
      ],
    },
    analysis: {
      eyebrow: '전략과 분석',
      title: <>전략을 기록하고,<br /><span>실행과 함께 검토하세요.</span></>,
      copy: '플레이북의 전략 버전과 실제 거래를 연결하고, 같은 데이터 정의를 쓰는 분석 화면에서 패턴과 근거를 살펴봅니다.',
      screenshotEyebrow: '청산 후 보유 결과',
      screenshotTitle: '청산이 빨랐는지 추측하지 않습니다.',
      screenshotCopy: '실제 청산 시점과 이후 1~10개 완료 봉을 더 보유했을 때의 평균 결과를 15분·1시간·2시간·4시간·일봉별로 비교합니다.',
      screenshotAlt: '실제 청산과 이후 완료 봉의 평균 결과를 비교하는 Trade Journal 청산 후 보유 분석 화면',
      openImage: '청산 후 보유 분석 화면 크게 보기',
      stories: [
        ['전략 플레이북', '진입·리스크·청산 규칙을 버전으로 보존하고, 각 거래에 실제 사용한 버전을 연결합니다.', '버전별 규칙'],
        ['규칙 준수 분석', '규칙 엔진이 기록된 사실로 준수·위반·판정 불가를 구분해 실행 과정을 검토합니다.', '준수 · 위반'],
        ['분석 작업공간', '성과 지표를 전략·규칙·장세·진입 유형 등으로 비교하고 패턴 후보를 근거 거래와 연결합니다.', '패턴 · 근거'],
      ],
      evidence: '거래 복기는 관찰된 패턴과 전략·실행 진단을 한곳에 모으고, 각 결과를 근거 거래로 이어 줍니다.',
    },
    plan: {
      eyebrow: '계획 분석 · 실험',
      title: <>계획하고, 바꾸고,<br /><span>같은 기준으로 측정하세요.</span></>,
      copy: '계획 분석에서 손절가·목표가·최대 보유시간을 기록하고 실제 실행과 비교합니다. 관찰된 문제는 가설·기준 기간·측정 조건을 고정한 행동 실험으로 만들고 측정 화면에서 이전 기간과 비교할 수 있습니다.',
      note: '사전 계획과 회고 기록을 구분하며, 측정 결과는 인과관계를 증명하지 않습니다.',
      planned: '계획',
      actual: '실제 실행',
      labels: ['손절', '진입', '1차 목표', '2차 목표', '최대 보유'],
      actualLabels: ['손절 이동', '부분 청산', '최종 종료'],
    },
    security: {
      eyebrow: '로컬 우선 보안',
      title: <>거래 기록을 읽습니다.<br /><span>거래 권한은 필요하지 않습니다.</span></>,
      copy: 'Trade Journal은 주문을 실행하는 서비스가 아니라 종료 거래를 복기하는 데스크톱 앱입니다. 동기화 요청은 사용자가 선택한 거래소와 직접 통신하며, 이 소개 사이트는 API 키나 거래 기록을 수집하지 않습니다.',
      items: [
        ['읽기 전용 API', '거래 기록 조회 권한만 사용합니다.'],
        ['주문·취소·출금 없음', '거래 실행 권한을 요구하거나 사용하지 않습니다.'],
        ['로컬 SQLite 저장', '거래 기록과 분석 결과는 내 컴퓨터에 남습니다.'],
        ['보호된 자격 증명 저장', 'Windows 앱은 API 자격 증명을 자격 증명 관리자에 보관하며 브라우저 저장소에 두지 않습니다.'],
      ],
      website: '웹사이트가 수집하는 거래 데이터',
      websiteValue: '없음',
      source: '소스 코드와 릴리스 기록 확인',
    },
    workflow: {
      eyebrow: '사용 방법',
      title: <>다운로드하고, 연결하고,<br /><span>지난 거래를 검토하세요.</span></>,
      steps: [
        ['다운로드', 'Windows ZIP을 받고 압축을 푼 뒤 Trade Journal을 실행합니다.'],
        ['연결', 'Deepcoin SWAP 또는 Binance에서 읽기 전용 API 키를 만들어 연결합니다. 첫 연결 성공 시 최근 30일 종료 거래를 한 번 가져옵니다.'],
        ['복기', '저널에서 전략 버전을 연결하고, 거래 복기와 계획 분석에서 패턴·규칙 준수·실행 차이를 근거 거래까지 확인합니다.'],
      ],
      safety: 'API를 만들 때 주문·선물 거래·출금 권한은 모두 끄세요. Trade Journal에는 읽기 권한만 필요합니다.',
      guideCta: '상세 설치·API 연결 가이드',
      guideCopy: 'Windows 설치부터 Deepcoin·Binance 연결, 첫 동기화와 문제 해결까지 별도 페이지에서 순서대로 확인하세요.',
    },
    release: {
      eyebrow: '현재 공개판',
      title: <>이미 만든 거래부터<br /><span>다시 살펴보세요.</span></>,
      copy: '무료 Windows 공개 베타입니다. 계정이나 결제 없이 시작할 수 있습니다.',
      version: '버전',
      platform: '지원 환경',
      size: '다운로드 크기',
      button: 'Windows ZIP 다운로드',
      source: 'GitHub 소스 및 릴리스',
      smartScreen: '현재 Windows 빌드는 코드 서명이 없어 처음 실행할 때 SmartScreen 경고가 표시될 수 있습니다. 공식 GitHub 릴리스에서 받은 파일인지 확인한 뒤 “추가 정보” → “실행”을 선택하세요.',
    },
    faq: {
      eyebrow: '자주 묻는 질문',
      title: <>시작하기 전에<br /><span>확인할 내용</span></>,
      items: [
        ['어떤 거래소를 지원하나요?', '현재 공개판은 Deepcoin SWAP과 Binance의 읽기 전용 거래 기록 동기화를 지원합니다.'],
        ['어떤 API 권한이 필요한가요?', '거래 기록 조회에 필요한 읽기 전용 권한만 사용하세요. 주문·취소·선물 거래·출금 권한은 모두 비활성화해야 합니다.'],
        ['거래 데이터는 어디에 저장되나요?', '거래 기록과 분석 결과는 데스크톱 앱의 로컬 SQLite에 저장됩니다. 이 소개 사이트는 거래 데이터를 수집하지 않습니다.'],
        ['Trade Journal이 주문이나 출금을 실행할 수 있나요?', '아니요. Trade Journal은 주문·취소·출금 기능을 제공하지 않으며, 해당 권한을 요구하지도 않습니다.'],
        ['API 키는 어떻게 보관되나요?', 'Windows 앱은 API 키를 브라우저 저장소에 넣지 않고 Windows 자격 증명 관리자에 보관합니다. 동기화할 때 선택한 거래소 API와 직접 통신합니다.'],
        ['전략과 규칙은 어떻게 분석하나요?', '플레이북에서 전략 규칙과 버전을 만들고 거래에 실제 사용한 버전을 연결합니다. 규칙 엔진은 기록된 사실만으로 준수·위반·판정 불가를 구분합니다.'],
        ['실험 결과가 수익 개선의 원인을 증명하나요?', '아니요. 실험의 측정 기능은 고정한 지표와 조건으로 이전 기간과 현재 기간의 관찰값을 비교하며 인과관계를 증명하지 않습니다.'],
        ['Windows SmartScreen 경고가 뜨는 이유는 무엇인가요?', '현재 Windows 공개판은 코드 서명이 아직 없어 처음 실행할 때 경고가 표시될 수 있습니다. 공식 GitHub 릴리스의 파일인지 확인한 뒤 실행하세요.'],
        ['보조지표는 어떤 가격을 기준으로 계산하나요?', '거래 기록은 연결한 거래소에서 가져오며, 차트 복기와 RSI·MACD·Stoch RSI·Slow Stochastic 등 보조지표는 Binance USDT-M Futures 가격 데이터를 기준으로 계산·갱신합니다.'],
        ['처음 연결하면 무엇이 일어나나요?', '연결 검사가 성공하면 최근 30일의 종료 거래를 한 번 자동으로 동기화합니다. 이후에는 앱에서 동기화를 실행해 최신 기록을 가져올 수 있습니다.'],
        ['API 키를 삭제할 수 있나요?', '앱의 거래소 연결 관리에서 연결을 삭제하면 저장된 연결 정보도 함께 제거할 수 있습니다. 거래소에서도 해당 API 키를 폐기하는 것을 권장합니다.'],
      ],
    },
    final: {
      eyebrow: 'TRADE JOURNAL',
      title: '다음 거래 전에, 지난 거래를 먼저 보세요.',
      copy: '거래를 기록하고, 전략과 실행을 진단하고, 다음 행동 변화를 같은 기준으로 측정하세요.',
    },
    footer: {
      copy: '내 거래를 기록하고 분석하기 위한 오픈소스 데스크톱 도구.',
      privacy: '이 정적 사이트는 API 키나 거래 기록을 수집하지 않습니다.',
      disclaimer: '투자자문이나 자동매매 서비스가 아닙니다.',
      source: 'GitHub',
      contact: '문의',
    },
  },
  en: {
    skip: 'Skip to content',
    nav: {
      product: 'Product',
      analysis: 'Analysis',
      security: 'Security',
      workflow: 'How it works',
      faq: 'FAQ',
      download: 'Download for Windows',
    },
    hero: {
      eyebrow: 'WINDOWS PUBLIC BETA · FREE',
      title: <>Find the patterns in your trades.<br /><span>Build better rules.</span></>,
      copy: 'Import closed trades through read-only connections, journal them, and compare strategy rules with actual execution. Trading Review and the Analytics Workspace link observed patterns back to supporting trades.',
      secondary: 'See how it works',
      facts: ['No account required', 'Read-only API', 'Data stays local'],
      visualLabel: 'Real Trade Journal screen',
      visualTitle: 'Detailed trade analysis',
      visualCopy: 'Finding → evidence → individual trade',
      openImage: 'Open the real product screenshot',
      imageAlt: 'Trade Journal detailed trade analysis showing performance by market regime and supporting trades',
    },
    problem: {
      eyebrow: 'WHY TRADE JOURNAL',
      title: <>Memory is selective.<br /><span>Your trade history isn’t.</span></>,
      copy: '“This strategy works.” “I followed the plan.” “I struggle in this market.” Trading beliefs form quickly, but memory alone cannot separate strategy from execution.',
      questions: [
        ['What did I trade?', 'Review closed trades with plans, tags, strategies, and results'],
        ['Did I follow the strategy?', 'Evaluate adherence against the exact Playbook version assigned to each trade'],
        ['Was the loss strategy or execution?', 'Trace the Trading Review diagnosis to supporting trades'],
      ],
      closing: 'The analytics describe associations observed in your trade history. They do not establish causes or future performance.',
    },
    flow: {
      eyebrow: 'ONE REVIEW FLOW',
      title: <>Start with the trade.<br /><span>Finish by measuring change.</span></>,
      copy: 'Connect strategy, execution, the next plan, and a behavior experiment in one review loop.',
      steps: [
        ['Trade', 'Sync closed trades'],
        ['Journal', 'Plan · tags · strategy'],
        ['Review', 'Trading Review'],
        ['Diagnose', 'Strategy vs execution'],
        ['Plan', 'Plan Lab'],
        ['Experiment', 'Lock hypothesis · criteria'],
        ['Measure', 'Compare one definition'],
      ],
    },
    analysis: {
      eyebrow: 'STRATEGY & ANALYTICS',
      title: <>Record the strategy.<br /><span>Review it beside execution.</span></>,
      copy: 'Connect a Playbook version to each trade, then inspect patterns and evidence through analytical views that share the same data definitions.',
      screenshotEyebrow: 'RESULTS AFTER EXIT',
      screenshotTitle: 'Do not guess whether the exit was early.',
      screenshotCopy: 'Compare the recorded exit with the average result after holding 1–10 more completed candles across 15m, 1H, 2H, 4H, and 1D views.',
      screenshotAlt: 'Trade Journal analysis comparing the recorded exit with average results after additional completed candles',
      openImage: 'Open the post-exit analysis screenshot',
      stories: [
        ['Strategy Playbook', 'Preserve entry, risk, and exit rules as versions and link the version actually used to each trade.', 'VERSIONED RULES'],
        ['Rule adherence', 'The deterministic rule engine separates followed, violated, and not-evaluable outcomes from recorded facts.', 'FOLLOWED · VIOLATED'],
        ['Analytics Workspace', 'Compare metrics by strategy, rule, regime, setup, and other dimensions, then open the trades behind a pattern candidate.', 'PATTERN · EVIDENCE'],
      ],
      evidence: 'Trading Review brings observed patterns and strategy-versus-execution diagnoses together, with links to the supporting trades.',
    },
    plan: {
      eyebrow: 'PLAN LAB · EXPERIMENTS',
      title: <>Plan. Change.<br /><span>Measure with one definition.</span></>,
      copy: 'Record stop, targets, and maximum holding time in Plan Lab, then compare the plan with execution. Turn an observed issue into a behavior experiment with a locked hypothesis, baseline, and measurement criteria, and compare periods in Measure.',
      note: 'Pre-trade plans stay distinct from retrospective notes, and measurements do not prove causation.',
      planned: 'Planned',
      actual: 'Actual execution',
      labels: ['SL', 'ENTRY', 'TP1', 'TP2', 'MAX HOLD'],
      actualLabels: ['Stop moved', 'Partial exit', 'Final exit'],
    },
    security: {
      eyebrow: 'LOCAL-FIRST SECURITY',
      title: <>It reads trade records.<br /><span>It does not need trading access.</span></>,
      copy: 'Trade Journal is a desktop review tool, not an execution service. Sync requests communicate directly with the exchange selected by the user. This marketing website does not collect API keys or trade records.',
      items: [
        ['Read-only API', 'Only trade-history access is needed.'],
        ['No orders, cancellations, or withdrawals', 'Execution permissions are neither required nor used.'],
        ['Local SQLite storage', 'Trade records and analysis stay on your computer.'],
        ['Protected credential storage', 'The Windows app keeps credentials in Credential Manager and out of browser storage.'],
      ],
      website: 'Trade data collected by this website',
      websiteValue: 'None',
      source: 'Inspect source code and release history',
    },
    workflow: {
      eyebrow: 'HOW IT WORKS',
      title: <>Download. Connect.<br /><span>Review the trades you made.</span></>,
      steps: [
        ['Download', 'Get the Windows ZIP, extract it, and launch Trade Journal.'],
        ['Connect', 'Create a read-only API key for Deepcoin SWAP or Binance. The first successful connection imports the recent 30 days of closed trades once.'],
        ['Review', 'Link the Playbook version in Journal, then use Trading Review and Plan Lab to trace patterns, rule adherence, and execution gaps to supporting trades.'],
      ],
      safety: 'Keep order, futures trading, and withdrawal permissions disabled when you create the API key. Trade Journal only needs read access.',
      guideCta: 'Detailed setup and API connection guide',
      guideCopy: 'Follow Windows setup, Deepcoin and Binance connection, first sync, and troubleshooting on a dedicated page.',
    },
    release: {
      eyebrow: 'CURRENT PUBLIC BUILD',
      title: <>Start with the trades<br /><span>you already made.</span></>,
      copy: 'A free Windows public beta. No account or payment is required.',
      version: 'Version',
      platform: 'Platform',
      size: 'Download size',
      button: 'Download Windows ZIP',
      source: 'GitHub source and releases',
      smartScreen: 'The current Windows build is not code-signed, so SmartScreen may warn on first launch. Verify that the file came from the official GitHub Releases page, then choose “More info” → “Run anyway”.',
    },
    faq: {
      eyebrow: 'FAQ',
      title: <>What to know<br /><span>before you start</span></>,
      items: [
        ['Which exchanges are supported?', 'The current public build supports read-only trade-history sync for Deepcoin SWAP and Binance.'],
        ['Which API permissions do I need?', 'Use only the Read Only permissions needed for trade history. Keep order, cancellation, futures trading, and withdrawal permissions disabled.'],
        ['Where is my trade data stored?', 'Trade records and analysis results are stored in the desktop app’s local SQLite database. This marketing website does not collect trading data.'],
        ['Can Trade Journal place orders or make withdrawals?', 'No. Trade Journal does not provide order, cancellation, or withdrawal functions and does not require those permissions.'],
        ['How are API keys stored?', 'The Windows app keeps API keys out of browser storage and stores them in Windows Credential Manager. Sync requests communicate directly with the selected exchange API.'],
        ['How are strategies and rules analyzed?', 'Create versioned strategy rules in Playbook and link the version actually used to a trade. The rule engine separates followed, violated, and not-evaluable outcomes using recorded facts.'],
        ['Does an experiment prove what improved results?', 'No. Measure compares observed values between the current and baseline periods using locked metrics and conditions; it does not establish causation.'],
        ['Why does Windows SmartScreen show a warning?', 'The current Windows public build is not code-signed yet, so Windows may warn on first launch. Verify that the file came from the official GitHub Releases page before opening it.'],
        ['Which price source is used for indicators?', 'Trade history comes from the connected exchange. Chart replay and indicators such as RSI, MACD, Stoch RSI, and Slow Stochastic are calculated and refreshed with Binance USDT-M Futures price data.'],
        ['What happens after the first connection?', 'After a successful connection check, Trade Journal imports the recent 30 days of closed trades once. Run sync in the app later to refresh your records.'],
        ['Can I delete an API key?', 'Delete the exchange connection in the app to remove the saved connection details. Revoking the key at the exchange is also recommended.'],
      ],
    },
    final: {
      eyebrow: 'TRADE JOURNAL',
      title: 'Review the last trade before placing the next one.',
      copy: 'Journal trades, diagnose strategy and execution, and measure the next behavior change with the same criteria.',
    },
    footer: {
      copy: 'An open-source desktop tool for recording and analyzing your own trades.',
      privacy: 'This static website does not collect API keys or trade records.',
      disclaimer: 'Not investment advice or an automated trading service.',
      source: 'GitHub',
      contact: 'Contact',
    },
  },
} as const;
