export type Language = 'ko' | 'en';

export const content = {
  ko: {
    skip: '본문으로 건너뛰기',
    nav: {
      product: '제품',
      analysis: '분석',
      security: '보안',
      workflow: '사용 방법',
      faq: 'FAQ',
      download: 'Windows 다운로드',
    },
    hero: {
      eyebrow: 'WINDOWS 공개 베타 · 무료',
      title: <>내 거래에서 <br className="mobile-only" />패턴을 찾고,<br /><span>더 나은 기준을 만드세요.</span></>,
      copy: '종료 거래를 가져와 전체 성과를 보고, 결과를 만든 개별 거래까지 추적하세요. Trade Journal은 당신의 거래 기록을 검토 가능한 증거로 바꿉니다.',
      secondary: '어떻게 작동하나요?',
      facts: ['회원가입 불필요', '읽기 전용 API', '내 컴퓨터에 저장'],
      visualLabel: '실제 Trade Journal 화면',
      visualTitle: '상세 거래 분석',
      visualCopy: '결론 → 근거 → 실제 거래까지',
      openImage: '실제 제품 화면 크게 보기',
      imageAlt: '시장 상황별 성과와 근거 거래를 보여주는 Trade Journal 상세 거래 분석 화면',
    },
    problem: {
      eyebrow: '왜 Trade Journal인가',
      title: <>기억은 선택적이지만,<br /><span>거래 기록은 그렇지 않습니다.</span></>,
      copy: '“이 셋업은 잘 맞는다”, “그 청산은 너무 빨랐다”, “이 장세에서는 약하다.” 매매에 대한 확신은 쉽게 생기지만, 기억만으로는 검증하기 어렵습니다.',
      questions: [
        ['이 셋업은 정말 반복해서 작동했나?', '거래별 결과와 조건을 함께 확인'],
        ['청산이 빨랐던 건가, 한 번의 아쉬움인가?', '청산 뒤 완료 봉의 평균 결과로 비교'],
        ['어떤 장세에서 내 방식이 흔들렸나?', '주봉·일봉·4시간봉 흐름별 성과 확인'],
      ],
      closing: 'Trade Journal은 느낌을 없애는 도구가 아니라, 느낌을 검토할 수 있게 만드는 도구입니다.',
    },
    flow: {
      eyebrow: '하나의 검토 흐름',
      title: <>거래 목록에서 끝나지 않고,<br /><span>판단의 근거까지 내려갑니다.</span></>,
      copy: '전체 숫자에서 시작해 반복되는 조건을 찾고, 그 조건을 만든 실제 거래를 다시 봅니다.',
      steps: [
        ['거래', '종료 거래 동기화'],
        ['성과', '기간 PnL · 승률 · PF'],
        ['패턴', '장세 · 진입 · 청산'],
        ['근거', '조건에 해당한 거래'],
        ['기준', '다음 복기 규칙'],
      ],
    },
    analysis: {
      eyebrow: '깊이 있는 분석',
      title: <>결과만 보지 말고,<br /><span>결과가 만들어진 맥락까지.</span></>,
      copy: '좋았던 거래와 나빴던 거래를 구분하는 조건을 찾고, 집계 결과를 개별 거래와 연결합니다.',
      screenshotEyebrow: '청산 후 보유 결과',
      screenshotTitle: '청산이 빨랐는지 추측하지 않습니다.',
      screenshotCopy: '실제 청산 시점과 이후 1~10개 완료 봉을 더 보유했을 때의 평균 결과를 15분·1시간·2시간·4시간·일봉별로 비교합니다.',
      screenshotAlt: '실제 청산과 이후 완료 봉의 평균 결과를 비교하는 Trade Journal 청산 후 보유 분석 화면',
      openImage: '청산 후 보유 분석 화면 크게 보기',
      stories: [
        ['시장 흐름', '주봉·일봉·4시간봉 조합으로 어떤 장세에서 내 매매가 잘 작동했는지 봅니다.', 'REGIME'],
        ['진입의 질', '진입 뒤 유리한 움직임과 불리한 움직임을 수익·손실 거래별로 비교합니다.', 'MFE / MAE'],
        ['지표와 기대값', 'RSI, MACD, VWAP 등 진입 조건과 실제 경로 기반 SL·TP 기대값을 함께 검토합니다.', 'RSI · MACD · SL/TP'],
      ],
      evidence: '모든 집계는 결과를 만든 근거 거래와 개별 차트 복기로 이어집니다.',
    },
    plan: {
      eyebrow: 'PLAN LAB',
      title: <>계획은 거래 전에.<br /><span>평가는 거래 후에.</span></>,
      copy: '진행 중인 거래에 의도한 SL, TP1, TP2, 최대 보유시간을 직접 기록합니다. 거래가 끝나면 계획과 실제 실행의 차이를 비교해 복기합니다.',
      note: '과거 거래의 계획을 자동으로 추측하지 않습니다.',
      planned: '계획',
      actual: '실제 실행',
      labels: ['SL', 'ENTRY', 'TP1', 'TP2', 'MAX HOLD'],
      actualLabels: ['손절 이동', '부분 청산', '최종 종료'],
    },
    security: {
      eyebrow: 'LOCAL-FIRST SECURITY',
      title: <>거래 기록을 읽습니다.<br /><span>거래 권한은 필요하지 않습니다.</span></>,
      copy: 'Trade Journal은 주문을 실행하는 서비스가 아니라, 종료 거래를 복기하는 데스크톱 앱입니다. 이 소개 사이트는 API Key나 거래 기록을 수집하지 않습니다.',
      items: [
        ['읽기 전용 API', '거래 기록 조회 권한만 사용합니다.'],
        ['주문·취소·출금 없음', '거래 실행 권한을 요구하거나 사용하지 않습니다.'],
        ['로컬 SQLite 저장', '거래 기록과 분석 결과는 내 컴퓨터에 남습니다.'],
        ['운영체제 보안 저장소 우선', 'API 자격 증명은 브라우저 저장소에 두지 않습니다.'],
      ],
      website: '웹사이트가 수집하는 거래 데이터',
      websiteValue: '없음',
      source: '소스 코드와 릴리스 기록 확인',
    },
    workflow: {
      eyebrow: '사용 방법',
      title: <>다운로드하고, 연결하고,<br /><span>지난 거래를 검토하세요.</span></>,
      steps: [
        ['다운로드', 'Windows ZIP을 받고 압축을 푼 뒤 Trade Journal을 실행합니다.'],
        ['연결', 'Deepcoin SWAP 또는 Binance에서 읽기 전용 API Key를 만들어 연결합니다. 첫 연결 성공 시 최근 30일 종료 거래를 한 번 가져옵니다.'],
        ['복기', '기간 성과에서 패턴을 찾고, 근거 거래와 개별 차트까지 확인합니다.'],
      ],
      safety: 'API를 만들 때 주문·선물 거래·출금 권한은 모두 끄세요. Trade Journal에는 읽기 권한만 필요합니다.',
      guideCta: '상세 설치·API 연결 가이드',
      guideCopy: 'Windows 설치부터 Deepcoin·Binance 연결, 첫 동기화와 문제 해결까지 별도 페이지에서 순서대로 확인하세요.',
    },
    release: {
      eyebrow: '현재 공개판',
      title: <>이미 만든 거래부터<br /><span>다시 살펴보세요.</span></>,
      copy: '무료 Windows 공개 베타입니다. 계정이나 결제 없이 시작할 수 있습니다.',
      version: '버전',
      platform: '지원 환경',
      size: '다운로드 크기',
      button: 'Windows ZIP 다운로드',
      source: 'GitHub 소스 및 릴리스',
      smartScreen: '현재 Windows 빌드는 코드 서명이 없어 처음 실행할 때 SmartScreen 경고가 표시될 수 있습니다. 공식 GitHub Releases에서 받은 파일인지 확인한 뒤 “추가 정보” → “실행”을 선택하세요.',
    },
    faq: {
      eyebrow: 'FAQ',
      title: <>시작하기 전에<br /><span>확인할 내용</span></>,
      items: [
        ['어떤 거래소를 지원하나요?', '현재 공개판은 Deepcoin SWAP과 Binance의 읽기 전용 거래 기록 동기화를 지원합니다.'],
        ['어떤 API 권한이 필요한가요?', '거래 기록 조회에 필요한 Read Only 권한만 사용하세요. 주문·취소·선물 거래·출금 권한은 모두 비활성화해야 합니다.'],
        ['거래 데이터는 어디에 저장되나요?', '거래 기록과 분석 결과는 데스크톱 앱의 로컬 SQLite에 저장됩니다. 이 소개 사이트는 거래 데이터를 수집하지 않습니다.'],
        ['Trade Journal이 주문이나 출금을 실행할 수 있나요?', '아니요. Trade Journal은 주문·취소·출금 기능을 제공하지 않으며, 해당 권한을 요구하지도 않습니다.'],
        ['API Key는 어떻게 보관되나요?', 'Trade Journal은 브라우저 저장소에 키를 넣지 않고 macOS Keychain과 Windows Credential Manager 같은 운영체제 보안 저장소 사용을 우선합니다.'],
        ['Windows SmartScreen 경고가 뜨는 이유는 무엇인가요?', '현재 Windows 공개판은 코드 서명이 아직 없어 처음 실행할 때 경고가 표시될 수 있습니다. 공식 GitHub Releases의 파일인지 확인한 뒤 실행하세요.'],
        ['보조지표는 어떤 가격을 기준으로 계산하나요?', '거래 기록은 연결한 거래소에서 가져오며, 차트 복기와 RSI·MACD·Stoch RSI·Slow Stochastic 등 보조지표는 Binance USDT-M Futures 가격 데이터를 기준으로 계산·갱신합니다.'],
        ['처음 연결하면 무엇이 일어나나요?', '연결 검사가 성공하면 최근 30일의 종료 거래를 한 번 자동으로 동기화합니다. 이후에는 앱에서 동기화를 실행해 최신 기록을 가져올 수 있습니다.'],
        ['API Key를 삭제할 수 있나요?', '앱의 거래소 연결 관리에서 연결을 삭제하면 저장된 연결 정보도 함께 제거할 수 있습니다. 거래소에서도 해당 API Key를 폐기하는 것을 권장합니다.'],
      ],
    },
    final: {
      eyebrow: 'TRADE JOURNAL',
      title: '다음 거래 전에, 지난 거래를 먼저 보세요.',
      copy: '내 거래에서 패턴을 찾고, 검토할 수 있는 기준을 만드세요.',
    },
    footer: {
      copy: '내 거래를 기록하고 분석하기 위한 오픈소스 데스크톱 도구.',
      privacy: '이 정적 사이트는 API Key나 거래 기록을 수집하지 않습니다.',
      disclaimer: '투자자문이나 자동매매 서비스가 아닙니다.',
      source: 'GitHub',
      contact: '문의',
    },
  },
  en: {
    skip: 'Skip to content',
    nav: {
      product: 'Product',
      analysis: 'Analysis',
      security: 'Security',
      workflow: 'How it works',
      faq: 'FAQ',
      download: 'Download for Windows',
    },
    hero: {
      eyebrow: 'WINDOWS PUBLIC BETA · FREE',
      title: <>Find the patterns in your trades.<br /><span>Build better rules.</span></>,
      copy: 'Import closed trades, understand the whole result, and trace every finding back to the trades behind it. Trade Journal turns your trading history into evidence you can review.',
      secondary: 'See how it works',
      facts: ['No account required', 'Read-only API', 'Data stays local'],
      visualLabel: 'Real Trade Journal screen',
      visualTitle: 'Detailed trade analysis',
      visualCopy: 'Finding → evidence → individual trade',
      openImage: 'Open the real product screenshot',
      imageAlt: 'Trade Journal detailed trade analysis showing performance by market regime and supporting trades',
    },
    problem: {
      eyebrow: 'WHY TRADE JOURNAL',
      title: <>Memory is selective.<br /><span>Your trade history isn’t.</span></>,
      copy: '“This setup works for me.” “That exit was too early.” “I struggle in this market.” Trading beliefs form quickly, but memory alone is a poor way to test them.',
      questions: [
        ['Did that setup actually work repeatedly?', 'Review the condition beside each result'],
        ['Was the exit early, or just memorable?', 'Compare the average result after completed candles'],
        ['Where does my process break down?', 'Inspect performance by Weekly, Daily, and 4H context'],
      ],
      closing: 'Trade Journal does not remove judgment. It gives you evidence to examine it.',
    },
    flow: {
      eyebrow: 'ONE REVIEW FLOW',
      title: <>Go beyond the trade list.<br /><span>Reach the evidence behind the result.</span></>,
      copy: 'Start with the aggregate result, find recurring conditions, and reopen the trades that produced them.',
      steps: [
        ['Trades', 'Sync closed trades'],
        ['Performance', 'Period PnL · win rate · PF'],
        ['Patterns', 'Regime · entry · exit'],
        ['Evidence', 'Trades behind the finding'],
        ['Process', 'Criteria for the next review'],
      ],
    },
    analysis: {
      eyebrow: 'DEEP ANALYSIS',
      title: <>Review the result—<br /><span>and the context that produced it.</span></>,
      copy: 'Find the conditions that separate stronger trades from weaker ones, then connect each aggregate finding to the individual trades behind it.',
      screenshotEyebrow: 'RESULTS AFTER EXIT',
      screenshotTitle: 'Do not guess whether the exit was early.',
      screenshotCopy: 'Compare the recorded exit with the average result after holding 1–10 more completed candles across 15m, 1H, 2H, 4H, and 1D views.',
      screenshotAlt: 'Trade Journal analysis comparing the recorded exit with average results after additional completed candles',
      openImage: 'Open the post-exit analysis screenshot',
      stories: [
        ['Market regime', 'Use Weekly, Daily, and 4H context to see where your trading has worked best.', 'REGIME'],
        ['Entry quality', 'Compare favorable and adverse movement after entry across winning and losing trades.', 'MFE / MAE'],
        ['Indicators and expectancy', 'Review RSI, MACD, VWAP, and other entry conditions beside path-based stop and target expectancy.', 'RSI · MACD · SL/TP'],
      ],
      evidence: 'Every aggregate finding can lead to its supporting trades and an individual chart replay.',
    },
    plan: {
      eyebrow: 'PLAN LAB',
      title: <>Plan before the trade.<br /><span>Review after it closes.</span></>,
      copy: 'Record intended SL, TP1, TP2, and maximum holding time for an active trade. After it closes, compare the plan with the actual execution.',
      note: 'Trade Journal never reconstructs past plans automatically.',
      planned: 'Planned',
      actual: 'Actual execution',
      labels: ['SL', 'ENTRY', 'TP1', 'TP2', 'MAX HOLD'],
      actualLabels: ['Stop moved', 'Partial exit', 'Final exit'],
    },
    security: {
      eyebrow: 'LOCAL-FIRST SECURITY',
      title: <>It reads trade records.<br /><span>It does not need trading access.</span></>,
      copy: 'Trade Journal is a desktop review tool, not an execution service. This marketing website does not collect API keys or trade records.',
      items: [
        ['Read-only API', 'Only trade-history access is needed.'],
        ['No orders, cancellations, or withdrawals', 'Execution permissions are neither required nor used.'],
        ['Local SQLite storage', 'Trade records and analysis stay on your computer.'],
        ['OS secure storage first', 'Credentials are kept out of browser storage.'],
      ],
      website: 'Trade data collected by this website',
      websiteValue: 'None',
      source: 'Inspect source code and release history',
    },
    workflow: {
      eyebrow: 'HOW IT WORKS',
      title: <>Download. Connect.<br /><span>Review the trades you made.</span></>,
      steps: [
        ['Download', 'Get the Windows ZIP, extract it, and launch Trade Journal.'],
        ['Connect', 'Create a read-only API key for Deepcoin SWAP or Binance. The first successful connection imports the recent 30 days of closed trades once.'],
        ['Review', 'Move from period performance to patterns, supporting trades, and individual chart replay.'],
      ],
      safety: 'Keep order, futures trading, and withdrawal permissions disabled when you create the API key. Trade Journal only needs read access.',
      guideCta: 'Detailed setup and API connection guide',
      guideCopy: 'Follow Windows setup, Deepcoin and Binance connection, first sync, and troubleshooting on a dedicated page.',
    },
    release: {
      eyebrow: 'CURRENT PUBLIC BUILD',
      title: <>Start with the trades<br /><span>you already made.</span></>,
      copy: 'A free Windows public beta. No account or payment is required.',
      version: 'Version',
      platform: 'Platform',
      size: 'Download size',
      button: 'Download Windows ZIP',
      source: 'GitHub source and releases',
      smartScreen: 'The current Windows build is not code-signed, so SmartScreen may warn on first launch. Verify that the file came from the official GitHub Releases page, then choose “More info” → “Run anyway”.',
    },
    faq: {
      eyebrow: 'FAQ',
      title: <>What to know<br /><span>before you start</span></>,
      items: [
        ['Which exchanges are supported?', 'The current public build supports read-only trade-history sync for Deepcoin SWAP and Binance.'],
        ['Which API permissions do I need?', 'Use only the Read Only permissions needed for trade history. Keep order, cancellation, futures trading, and withdrawal permissions disabled.'],
        ['Where is my trade data stored?', 'Trade records and analysis results are stored in the desktop app’s local SQLite database. This marketing website does not collect trading data.'],
        ['Can Trade Journal place orders or make withdrawals?', 'No. Trade Journal does not provide order, cancellation, or withdrawal functions and does not require those permissions.'],
        ['How are API keys stored?', 'Trade Journal keeps keys out of browser storage and prioritizes operating-system secure storage such as macOS Keychain and Windows Credential Manager.'],
        ['Why does Windows SmartScreen show a warning?', 'The current Windows public build is not code-signed yet, so Windows may warn on first launch. Verify that the file came from the official GitHub Releases page before opening it.'],
        ['Which price source is used for indicators?', 'Trade history comes from the connected exchange. Chart replay and indicators such as RSI, MACD, Stoch RSI, and Slow Stochastic are calculated and refreshed with Binance USDT-M Futures price data.'],
        ['What happens after the first connection?', 'After a successful connection check, Trade Journal imports the recent 30 days of closed trades once. Run sync in the app later to refresh your records.'],
        ['Can I delete an API key?', 'Delete the exchange connection in the app to remove the saved connection details. Revoking the key at the exchange is also recommended.'],
      ],
    },
    final: {
      eyebrow: 'TRADE JOURNAL',
      title: 'Review the last trade before placing the next one.',
      copy: 'Find patterns in your own trades and build criteria you can examine.',
    },
    footer: {
      copy: 'An open-source desktop tool for recording and analyzing your own trades.',
      privacy: 'This static website does not collect API keys or trade records.',
      disclaimer: 'Not investment advice or an automated trading service.',
      source: 'GitHub',
      contact: 'Contact',
    },
  },
} as const;
